BEGIN;

ALTER TABLE public.assistant_knowledge_articles
  ADD COLUMN IF NOT EXISTS keywords text NOT NULL DEFAULT '';

CREATE OR REPLACE FUNCTION public.search_assistant_knowledge(
  p_query text,
  p_role text,
  p_product_mode text,
  p_limit integer DEFAULT 6
)
RETURNS TABLE (slug text, title text, body text, source_label text, source_path text, rank real)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH query AS (
    SELECT websearch_to_tsquery('english', left(coalesce(p_query, ''), 500)) AS value
  )
  SELECT a.slug, a.title, a.body, a.source_label, a.source_path,
    ts_rank_cd(to_tsvector('english', a.title || ' ' || a.body || ' ' || a.keywords), query.value) AS rank
  FROM public.assistant_knowledge_articles a, query
  WHERE a.status = 'published'
    AND query.value <> ''::tsquery
    AND (a.audience_roles @> ARRAY['all']::text[] OR p_role = ANY(a.audience_roles))
    AND (a.product_modes @> ARRAY['all']::text[] OR p_product_mode = ANY(a.product_modes))
    AND to_tsvector('english', a.title || ' ' || a.body || ' ' || a.keywords) @@ query.value
  ORDER BY rank DESC, a.title ASC
  LIMIT least(greatest(coalesce(p_limit, 6), 1), 10);
$$;

INSERT INTO public.assistant_knowledge_articles
  (slug, title, body, keywords, source_label, source_path, audience_roles, product_modes, status, approved_at)
VALUES
  ('app-navigation', 'Finding work in EveryStep', 'Today is the daily orientation view. Operations is the office and admin queue for scheduling, waiting, closeout, and attention. My Work is the field user list of assigned work. Training Room teaches workflows by role. Admin Center contains company setup and administrative workspaces. Use the view that matches the responsibility you are handling instead of treating every queue as one backlog.', 'where do I go menu navigation dashboard home today operations ops my work training admin center find page', 'EveryStep navigation knowledge', '/training', ARRAY['all'], ARRAY['all'], 'published', now()),
  ('today-daily-view', 'Using Today', 'Open Today before the day begins to understand what is scheduled, assigned, waiting, urgent, or ready for follow-up. Today is an orientation view; it does not replace the Operations queue or the field user My Work list.', 'today daily schedule start day dashboard urgent assigned waiting follow up what should I do first', 'EveryStep workflow knowledge', '/today', ARRAY['all'], ARRAY['all'], 'published', now()),
  ('operations-queue', 'Using Operations', 'Operations is the office and admin workspace for work needing scheduling, assignment, waiting follow-up, closeout, customer contact, or another operational decision. Field users finish their visit outcome; office or admin users decide the next operational step.', 'operations ops queue office dispatch backlog closeout pending waiting schedule attention next step', 'EveryStep workflow knowledge', '/ops', ARRAY['owner','admin','office','billing'], ARRAY['all'], 'published', now()),
  ('my-work', 'Using My Work', 'My Work shows work assigned to the signed-in field user. A technician or rater starts there or in Today, opens the assigned job, reviews the customer, location, and work context, records field information, and finishes the visit with the correct outcome.', 'my work technician tech field assigned jobs appointments where start rater', 'EveryStep field knowledge', '/ops/field', ARRAY['owner','admin','tech'], ARRAY['all'], 'published', now()),
  ('customers-and-locations', 'Customers and service locations', 'A customer is the account receiving service. A service location is the physical place where work occurs. One customer may have multiple locations. Job intake can create or select both while keeping the new job connected. Users may also add a customer separately when building the customer list before scheduling work.', 'customer client homeowner property address service location site multiple locations add customer contact', 'EveryStep customer knowledge', '/customers', ARRAY['owner','admin','office'], ARRAY['all'], 'published', now()),
  ('job-intake', 'Creating a job', 'Use job intake when the goal is to run work. Select or create the customer, confirm the service location, enter the work context, then create the job. Schedule and assign it when appointment and staffing details are known. Creating a job does not issue an invoice or collect payment.', 'new job create job intake service call work order customer location appointment', 'EveryStep job knowledge', '/jobs/new', ARRAY['owner','admin','office'], ARRAY['all'], 'published', now()),
  ('scheduling-and-assignment', 'Scheduling and assigning work', 'Office, dispatcher, owner, or admin users schedule work and assign the appropriate field user. Today and Operations help identify unassigned or unscheduled work. Assignment determines whose My Work list should show the job; it does not change billing authority.', 'calendar schedule appointment dispatch assign technician tech unassigned unscheduled date time', 'EveryStep scheduling knowledge', '/ops', ARRAY['owner','admin','office'], ARRAY['all'], 'published', now()),
  ('job-field-record', 'Working inside a job', 'The job page is the operational record for the visit. Review the customer, service location, scope, schedule, and assignment before work. Capture relevant notes, photos, equipment context, diagnostics, and work details in their designated job areas. Do not duplicate or invent information merely to complete a screen.', 'job detail page notes photos diagnostics work details scope visit field record attachments evidence', 'EveryStep field knowledge', '/ops/field', ARRAY['owner','admin','office','tech'], ARRAY['all'], 'published', now()),
  ('field-finish-outcomes', 'Choosing a field finish outcome', 'Use Work Completed when the field responsibility for today is finished. Use Materials or Parts Needed when a required item prevents completion. Use Approval Needed when an approval decision is required. Use Unable to Complete or Other for another unresolved reason. A finish outcome completes the field visit responsibility and routes follow-up; it does not automatically create a return visit, invoice, or payment.', 'finish complete outcome work completed parts materials needed approval needed unable cannot finish other', 'EveryStep field knowledge', '/ops/field', ARRAY['owner','admin','office','tech'], ARRAY['all'], 'published', now()),
  ('closeout-handoff', 'Closeout after field work', 'After field work, office or admin reviews what happened and chooses the next step: close the job, contact the customer, handle waiting work, arrange return work, or hand completed commercial work to billing. Billing and payment truth remain separate from the technician finish outcome.', 'after field work closeout handoff return visit follow up office billing job complete', 'EveryStep closeout knowledge', '/ops', ARRAY['owner','admin','office','billing'], ARRAY['all'], 'published', now()),
  ('pricebook', 'Using the Pricebook', 'The Pricebook stores reusable items and default commercial descriptions, types, units, and prices. Selecting a Pricebook item copies its current defaults into the estimate or supported workflow as a snapshot. A manual line may be used when no appropriate Pricebook item exists. Review scope and price before saving.', 'price book pricebook catalog default item service material install labor manual line saved item pricing', 'EveryStep commercial knowledge', '/ops/admin/pricebook', ARRAY['owner','admin','office','billing','tech'], ARRAY['all'], 'published', now()),
  ('estimate-building', 'Building an estimate', 'An estimate is proposed commercial scope. Add clear line names, customer-facing descriptions, quantities, and prices. Pricebook items may provide defaults, while manual lines support one-off work. Review the customer, location, scope, recipient, totals, and proposal wording before sending. Estimate lines are not completed Work Items or Invoice Charges.', 'estimate quote proposal bid create line description quantity price scope send readiness', 'EveryStep estimate knowledge', '/estimates', ARRAY['owner','admin','office','billing','tech'], ARRAY['all'], 'published', now()),
  ('estimate-options', 'Good, Better, and Best estimate options', 'Option packages let the user present meaningful alternatives. Each option should have a clear label, short summary, included line items, and an intentional difference in value or scope. Avoid creating three nearly identical choices. The customer or authorized operator selects through the existing proposal workflow; AI cannot approve an option.', 'good better best options package choice proposal alternate upgrade basic premium', 'EveryStep estimate knowledge', '/estimates', ARRAY['owner','admin','office','billing','tech'], ARRAY['all'], 'published', now()),
  ('estimate-ai-rewrite', 'Using Estimate Coach', 'In a draft estimate line, enter rough field notes and choose Rewrite for customer. Estimate Coach returns concise proposed wording and lists important missing specifics below it. Use rewrite applies the text only to the unsaved form; the user must still review and save the line. Whole-estimate coaching appears after estimate entry. AI never sends, approves, converts, invoices, or collects payment.', 'estimate coach AI rewrite customer wording rough notes use rewrite try again missing details', 'EveryStep assistant knowledge', '/estimates', ARRAY['owner','admin','office','billing','tech'], ARRAY['all'], 'published', now()),
  ('invoice-workflow', 'Invoices and invoice review', 'Invoices are financial records separate from jobs, field outcomes, and estimates. Authorized users review invoice charges and status from the supported job or invoice workspace. Creating or completing field work does not automatically mean an invoice is issued, sent, or paid. Follow the account invoice mode and explicit invoice actions.', 'invoice bill billing charges draft issue send paid job estimate conversion accounts receivable AR', 'EveryStep billing knowledge', '/ops', ARRAY['owner','admin','billing'], ARRAY['all'], 'published', now()),
  ('payments', 'Payments and payment attention', 'Authorized billing, owner, or admin users review payment status and financial follow-through. A successful payment is recorded money; a failed attempt creates attention and is not collected money. Online invoice payments require the account payment setup and an eligible invoice. Technicians do not own payment setup unless separately authorized.', 'payment card online pay stripe failed payment collected money refund billing AR payment attention', 'EveryStep payment knowledge', '/reports/payments', ARRAY['owner','admin','billing'], ARRAY['all'], 'published', now()),
  ('financial-access', 'Why billing or payments may be hidden', 'Billing and payment views are limited to users with financial responsibility. A hidden financial surface may reflect the signed-in role or capability rather than missing data. Ask an owner or admin to review access. The trainer cannot grant permissions or bypass a restriction.', 'cannot see billing payments hidden permission access denied role financial register', 'EveryStep security knowledge', '/training', ARRAY['all'], ARRAY['all'], 'published', now()),
  ('team-access', 'Team invitations and roles', 'Team and Access is the owner and admin area for inviting users and reviewing roles. Assign responsibilities deliberately so office, field, billing, and admin authority remain clear. The trainer can explain roles but cannot invite a user, activate an account, or change permissions.', 'invite employee teammate user team role permission access admin technician office billing', 'EveryStep security knowledge', '/ops/admin/users', ARRAY['owner','admin'], ARRAY['all'], 'published', now()),
  ('company-profile', 'Company Profile and account setup', 'Company Profile is where owners and admins review business identity, support contact details, invoice posture, payment setup, and other company settings. Launch Room separates Required Now setup from Recommended Next and Can Wait so optional configuration does not block the first job.', 'company profile business information settings setup launch room required now can wait subscription', 'EveryStep setup knowledge', '/ops/admin/company-profile', ARRAY['owner','admin'], ARRAY['all'], 'published', now()),
  ('notifications-and-device', 'Notifications and field device setup', 'The account area contains user and device-related setup. Notifications help field users see assignments and mentions. A user should review device permissions and notification settings on the device they use for work. Notification setup does not change job assignment or role authority.', 'notification alerts phone device mobile setup push mention assignment account settings', 'EveryStep field knowledge', '/account', ARRAY['all'], ARRAY['all'], 'published', now()),
  ('equipment-and-systems', 'Customer systems and equipment', 'Systems group equipment at a customer service location. Equipment records capture installed or serviced components and their known details. Keep equipment connected to the correct customer and location, and use job context when recording service or installation history. Do not guess model, serial, capacity, or installation facts.', 'equipment system unit furnace condenser coil model serial customer location asset installed product details', 'EveryStep equipment knowledge', '/customers', ARRAY['owner','admin','office','tech'], ARRAY['all'], 'published', now()),
  ('maintenance-agreements', 'Maintenance agreements and service plans', 'Maintenance agreements represent the customer service-plan relationship and planned service context. They do not by themselves prove a visit occurred, create completed work, or collect payment. Use the agreement and supported scheduling workflows according to the account configuration.', 'maintenance agreement membership service plan recurring visit tune up planned service contract', 'EveryStep service-plan knowledge', '/ops', ARRAY['owner','admin','office','billing'], ARRAY['all'], 'published', now()),
  ('ecc-testing', 'ECC and HERS testing workflow', 'ECC or HERS raters open assigned ECC jobs, enter results in the correct test area, and use the failed, correction, and retest flow when test truth requires it. A generic field outcome is not a substitute for an ECC failed result. Certification closeout remains separate from invoice or payment status.', 'ECC HERS rater test result pass fail correction retest certification cert compliance', 'EveryStep ECC/HERS knowledge', '/ops/field', ARRAY['owner','admin','office','tech'], ARRAY['ecc_hers','hybrid'], 'published', now()),
  ('ecc-handoff', 'ECC and HERS contractor handoff', 'The ECC/HERS setup area supports authorized rater relationships, connection codes, and contractor handoff when that workflow is enabled. Use the explicit connection and work-sharing flow. A handoff does not transfer unrestricted account authority or erase the originating job and test history.', 'ECC HERS contractor handoff workshare work sharing connected rater connection code return work', 'EveryStep ECC/HERS knowledge', '/ops/admin/company-profile', ARRAY['owner','admin','office','tech'], ARRAY['ecc_hers','hybrid'], 'published', now()),
  ('permits', 'Permit workflow', 'Permit work is owner-scoped and may be unavailable unless the account is enabled for it. Authorized internal users track permit requests and their supporting context. Permit status is separate from job completion, estimate approval, invoice payment, and ECC certification. The trainer cannot create or change a permit request.', 'permit request permit number jurisdiction inspection status needed not needed owner scoped', 'EveryStep permit knowledge', '/ops/admin', ARRAY['owner','admin','office'], ARRAY['all'], 'published', now()),
  ('customer-contact', 'Recording customer contact attempts', 'Use the supported contact-attempt workflow to record that the team called, emailed, texted, or otherwise tried to reach a customer. This helps office users see what has already been attempted. Recording an attempt does not prove the customer responded, approve work, or send a new message by itself.', 'customer contact attempt called call email text reached voicemail follow up communication', 'EveryStep communication knowledge', '/ops', ARRAY['owner','admin','office','billing'], ARRAY['all'], 'published', now()),
  ('reports', 'Using reports', 'Reports summarize operational or financial records for authorized users. Open the report that matches the question, apply its filters, and verify the underlying record when a decision requires detail. Report visibility follows role and financial-access boundaries. A report does not change source records.', 'report analytics totals dashboard payments revenue export csv filters financial operational', 'EveryStep reporting knowledge', '/reports', ARRAY['owner','admin','office','billing'], ARRAY['all'], 'published', now()),
  ('trainer-help-gaps', 'Trainer answers, feedback, and support', 'The trainer answers only from published EveryStep knowledge and cites the related app area. If the knowledge does not support an answer, it says the topic is not documented and creates a private draft for review when logging succeeds. Not Helpful and Still Need Help are review signals; they do not automatically create a support case or train the model.', 'trainer assistant ask CM unknown answer not helpful still need help support case feedback knowledge gap', 'EveryStep assistant policy', '/training', ARRAY['all'], ARRAY['all'], 'published', now())
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  keywords = EXCLUDED.keywords,
  source_label = EXCLUDED.source_label,
  source_path = EXCLUDED.source_path,
  audience_roles = EXCLUDED.audience_roles,
  product_modes = EXCLUDED.product_modes,
  status = 'published',
  approved_at = now(),
  updated_at = now();

COMMIT;
